import { Allocation } from "./types";

export const allocations: Allocation[] = [
  {
    id: "1",
    assetId: "AST-001",
    assetName: 'MacBook Pro 16" M3 Max',
    employeeName: "Sarah Chen",
    department: "Engineering",
    assignedSince: "2024-01-15",
    value: 3499,
    status: "Active",
  },
  {
    id: "2",
    assetId: "AST-002",
    assetName: "Dell XPS 15 9530",
    employeeName: "James Park",
    department: "Sales",
    assignedSince: "2023-11-08",
    value: 2199,
    status: "Active",
  },
  {
    id: "3",
    assetId: "AST-003",
    assetName: "Herman Miller Aeron",
    employeeName: "Maya Obi",
    department: "Design",
    assignedSince: "2022-09-01",
    value: 1895,
    status: "Active",
  },
  {
    id: "4",
    assetId: "AST-004",
    assetName: "Dell PowerEdge R750",
    employeeName: "IT Team",
    department: "Engineering",
    assignedSince: "2022-03-14",
    value: 12400,
    status: "Maintenance",
  },
  {
    id: "5",
    assetId: "AST-005",
    assetName: "iPhone 15 Pro Max",
    employeeName: "Raj Patel",
    department: "Sales",
    assignedSince: "2024-02-01",
    value: 1199,
    status: "Active",
  },
  {
    id: "6",
    assetId: "AST-006",
    assetName: 'LG UltraFine 32" 4K',
    employeeName: "Chris Lee",
    department: "Engineering",
    assignedSince: "2023-05-22",
    value: 799,
    status: "Active",
  },
  {
    id: "7",
    assetId: "AST-007",
    assetName: "HP LaserJet Enterprise M507",
    employeeName: "Shared",
    department: "Operations",
    assignedSince: "2021-11-30",
    value: 3200,
    status: "Maintenance",
  },
  {
    id: "8",
    assetId: "AST-008",
    assetName: 'MacBook Air 15"',
    employeeName: "Anna Miller",
    department: "Finance",
    assignedSince: "2024-03-19",
    value: 1299,
    status: "Reserved",
  },
  {
    id: "9",
    assetId: "AST-009",
    assetName: "ThinkPad X1 Carbon",
    employeeName: "David Kim",
    department: "HR",
    assignedSince: "2024-01-05",
    value: 1799,
    status: "Active",
  },
  {
    id: "10",
    assetId: "AST-010",
    assetName: "Samsung Galaxy S25 Ultra",
    employeeName: "Emily Davis",
    department: "Marketing",
    assignedSince: "2024-04-10",
    value: 1399,
    status: "Pending",
  },
  {
    id: "11",
    assetId: "AST-011",
    assetName: "iPad Pro 13",
    employeeName: "Michael Scott",
    department: "Management",
    assignedSince: "2024-02-15",
    value: 1499,
    status: "Active",
  },
  {
    id: "12",
    assetId: "AST-012",
    assetName: "Surface Laptop Studio",
    employeeName: "Sophia Brown",
    department: "Engineering",
    assignedSince: "2023-08-12",
    value: 2399,
    status: "Active",
  },
  {
    id: "13",
    assetId: "AST-013",
    assetName: "Canon EOS R8",
    employeeName: "Media Team",
    department: "Marketing",
    assignedSince: "2024-01-28",
    value: 1899,
    status: "Reserved",
  },
  {
    id: "14",
    assetId: "AST-014",
    assetName: "Lenovo Legion 7",
    employeeName: "Alex Turner",
    department: "Engineering",
    assignedSince: "2023-12-11",
    value: 2099,
    status: "Active",
  },
  {
    id: "15",
    assetId: "AST-015",
    assetName: "Dell Latitude 7440",
    employeeName: "Jennifer Adams",
    department: "Finance",
    assignedSince: "2024-03-01",
    value: 1599,
    status: "Pending",
  },
  {
    id: "16",
    assetId: "AST-016",
    assetName: "Mac Mini M4",
    employeeName: "QA Team",
    department: "Engineering",
    assignedSince: "2024-02-09",
    value: 999,
    status: "Active",
  },
  {
    id: "17",
    assetId: "AST-017",
    assetName: 'Dell 34" Ultrawide',
    employeeName: "Kevin White",
    department: "Design",
    assignedSince: "2023-07-16",
    value: 899,
    status: "Reserved",
  },
  {
    id: "18",
    assetId: "AST-018",
    assetName: "Logitech Rally Bar",
    employeeName: "Conference Room",
    department: "Operations",
    assignedSince: "2022-10-21",
    value: 4299,
    status: "Active",
  },
];