import { Department, Employee, StatCard } from "./types";

export const stats: StatCard[] = [
  {
    title: "Employees",
    value: "248",
    description: "+12 this month",
  },
  {
    title: "Departments",
    value: "8",
    description: "Across organization",
  },
  {
    title: "Assets",
    value: "643",
    description: "$1.24M assigned",
  },
];

export const departments: Department[] = [
  {
    id: 1,
    name: "All",
    employees: 248,
    assets: 643,
    assetValue: 1240000,
    color: "#111827",
  },
  {
    id: 2,
    name: "Engineering",
    employees: 82,
    assets: 210,
    assetValue: 420000,
    color: "#2563eb",
  },
  {
    id: 3,
    name: "Sales",
    employees: 44,
    assets: 92,
    assetValue: 185000,
    color: "#16a34a",
  },
  {
    id: 4,
    name: "Marketing",
    employees: 27,
    assets: 41,
    assetValue: 86000,
    color: "#db2777",
  },
  {
    id: 5,
    name: "Finance",
    employees: 18,
    assets: 32,
    assetValue: 91000,
    color: "#f59e0b",
  },
  {
    id: 6,
    name: "HR",
    employees: 21,
    assets: 26,
    assetValue: 54000,
    color: "#8b5cf6",
  },
  {
    id: 7,
    name: "Operations",
    employees: 36,
    assets: 98,
    assetValue: 201000,
    color: "#06b6d4",
  },
  {
    id: 8,
    name: "Legal",
    employees: 20,
    assets: 19,
    assetValue: 35000,
    color: "#ef4444",
  },
];

export const employees: Employee[] = [
  {
    id: 1,
    name: "Sarah Chen",
    email: "sarah@company.com",
    role: "Senior Software Engineer",
    department: "Engineering",
    assets: 4,
    assetValue: 9800,
    joined: "Mar 2021",
    status: "Active",
  },
  {
    id: 2,
    name: "James Park",
    email: "james@company.com",
    role: "Engineering Manager",
    department: "Engineering",
    assets: 5,
    assetValue: 12400,
    joined: "Jan 2020",
    status: "Active",
  },
  {
    id: 3,
    name: "Emma Wilson",
    email: "emma@company.com",
    role: "Product Designer",
    department: "Marketing",
    assets: 2,
    assetValue: 3100,
    joined: "Jul 2022",
    status: "Active",
  },
  {
    id: 4,
    name: "Raj Patel",
    email: "raj@company.com",
    role: "Sales Manager",
    department: "Sales",
    assets: 3,
    assetValue: 5600,
    joined: "Sep 2019",
    status: "On Leave",
  },
  {
    id: 5,
    name: "Maya Rodriguez",
    email: "maya@company.com",
    role: "Financial Analyst",
    department: "Finance",
    assets: 2,
    assetValue: 4100,
    joined: "Nov 2023",
    status: "Active",
  },
  {
    id: 6,
    name: "David Kim",
    email: "david@company.com",
    role: "HR Executive",
    department: "HR",
    assets: 1,
    assetValue: 1500,
    joined: "Apr 2022",
    status: "Inactive",
  },
  {
    id: 7,
    name: "Sophia Brown",
    email: "sophia@company.com",
    role: "Operations Lead",
    department: "Operations",
    assets: 6,
    assetValue: 17200,
    joined: "Feb 2020",
    status: "Active",
  },
  {
    id: 8,
    name: "Michael Scott",
    email: "michael@company.com",
    role: "Legal Advisor",
    department: "Legal",
    assets: 2,
    assetValue: 3400,
    joined: "Jun 2021",
    status: "Active",
  },
];